#!/bin/sh
index() {
  find "$1" -type f '(' -name '*.html' -or -name '*.shen' ')' \
  | awk -v dst_prefix="$2" -v dir="$1" '
  {
    to = from = $0
    sub("^" dir "/", dst_prefix, to);
    printf("{\"to\": \"%s\", \"from\": \"%s\"}\n", to, from);
  }'
}

{
  index fs .
} | awk '
BEGIN {print("[")}
NR != 1 {printf(",\n")}
{printf("  %s", $0)}
END {print("\n]")}
'
