#!/bin/sh
set -e
remote=origin
branch=master
assets='shen.js shen.html doc web examples'

git_sync() {
  git pull "$remote"
  git checkout gh-pages
  git checkout "$remote/$branch" -- $assets
  git rm --cached -r .
}

local_sync() {
  (cd ../shen-js && tar c $assets) | tar x
}

if test -d "../shen-js" ; then
  local_sync
else
  git_sync
fi

cp -r examples doc src/

export PATH=/home/ramil/bin:$PATH:/usr/plan9/bin
echo $PATH

mk srcdir=src
rm -rf fs
cp -r src fs
find fs -name '*.md' -delete
